### ISSUE TITLE
Adding email functionality and improving overall GUI

### ISSUE THREAD

**Issue by VibhorShukla-BHRT** [Kunal-agrawall/AI-Jarvis#28]
Hey @Kunal-agrawall !
I wanna add email functionality, where a user can just command the ai to 'send an email' to someone, ai gets their email and asks what to send them and send it. All by speech commands!
Also i saw minor grammatical flaws which i intend to correct in GUI and also give the site a new attractive look!
Please assign me this issue!
Looking forward to your guidance!

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.I have prior experience too as I have made 20+ Full-stack projects.

**Comment by Sailza** [comment]
As a contributor to GSSOC 2024, I'm eager to take on tasks. Could you please assign me this task for completion?
