### ISSUE TITLE
The whole button "Click here to speak" is not clickable

### ISSUE THREAD

**Issue by bhumika-1127** [Kunal-agrawall/AI-Jarvis#40]
In your website only the mic is clickable. For better user experience the whole button should function.
@Kunal-agrawall I wish to resolve this issue. Assign me this task under GSSOC'24 and kindly add labels to it. 
![image](https://github.com/Kunal-agrawall/AI-Jarvis/assets/137604220/af0108b4-5459-45db-a644-a9c75eb829ac)

**Comment by Riyasharma28** [comment]
Please assign this issue to me @Riyasharma28 under GSSoC'24.I have prior experience too as I have made 20+ Full-stack projects.

**Comment by chinmaya-704** [comment]
please assign this task to me under GSSoC'24 contributor so that I can help you make a better user friendly website.
